//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanLinhKienDienTu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberRank
    {
        public MemberRank()
        {
            this.Customers = new HashSet<Customer>();
        }
    
        public int RankID { get; set; }
        public string RankName { get; set; }
        public string RankNameEn { get; set; }
        public long MinSpending { get; set; }
        public Nullable<long> MaxSpending { get; set; }
        public decimal DiscountPercent { get; set; }
        public string IconUrl { get; set; }
        public string ColorCode { get; set; }
        public string Description { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<Customer> Customers { get; set; }
    }
}

